temp: disable SlowTests

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -301,70 +301,70 @@ jobs:
           name: IntegrationTests-results-${{ matrix.scalaVersion }}
           path: '**/it-reports/*.xml'
 
-  slowTests:
-    name: SlowTests
-    runs-on: ubuntu-latest
-    needs: [ build, setup ]
-    strategy:
-      matrix:
-        scalaVersion: ${{fromJson(needs.setup.outputs.scala_version_matrix)}}
-    env:
-      SCALA_VERSION: ${{ matrix.scalaVersion }}
-    if: ${{ needs.setup.outputs.fe_changes_count != needs.setup.outputs.all_changes_count || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/demo' || startsWith(github.ref, 'refs/heads/preview') || startsWith(github.ref, 'refs/heads/release') }}
-    steps:
-      - name: Cancel previous runs
-        if: github.event_name != 'push'
-        uses: styfle/cancel-workflow-action@0.11.0
-        with:
-          access_token: ${{ secrets.GITHUB_TOKEN }}
-      - uses: actions/checkout@v3
-      - uses: coursier/setup-action@v1
-        with:
-          jvm: temurin:1.11.0.17
-      - name: Cache ivy packages
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.ivy2/cache
-            ~/.cache/coursier
-            ~/.sbt
-          key: sbt-cache-${{ hashFiles('**/*.sbt') }}
-          restore-keys: sbt
-      - uses: actions/download-artifact@v3
-        with:
-          name: build-target
-      - name: Untar artifacts
-        shell: bash
-        run:  tar xfz target.tgz
-      # We run k8s tests here instead of in integrationTests job because it causes RAM overhead and some other docker tests failing occasionally
-      - uses: AbsaOSS/k3d-action@v2.4.0
-        env:
-          PROJECT_ROOT: ${{ github.workspace }}
-        with:
-          cluster-name: "k3s-default"
-          k3d-version: "v5.4.9" # default version - change with caution, there was some problem with 500 exit codes for after upgrade
-          args: >-
-            --config=.k3d/single-cluster.yml
-            --trace
-      - name: Slow tests
-        env:
-          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-        shell: bash
-        run: ./ciRunSbt.sh designer/Slow/test liteK8sDeploymentManager/ExternalDepsTests/test schemedKafkaComponentsUtils/ExternalDepsTests/test liteKafkaComponentsTests/ExternalDepsTests/test
-      - name: docker logs
-        if: success() || failure()
-        run: |
-          docker logs k3d-k3s-default-server-0
-          docker logs k3d-k3s-default-agent-0
-          docker logs k3d-k3s-default-serverlb
-      - name: Test Report
-        if: success() || failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: SlowTests-results-${{ matrix.scalaVersion }}
-          path: '**/test-reports/*.xml'
+#  slowTests:
+#    name: SlowTests
+#    runs-on: ubuntu-latest
+#    needs: [ build, setup ]
+#    strategy:
+#      matrix:
+#        scalaVersion: ${{fromJson(needs.setup.outputs.scala_version_matrix)}}
+#    env:
+#      SCALA_VERSION: ${{ matrix.scalaVersion }}
+#    if: ${{ needs.setup.outputs.fe_changes_count != needs.setup.outputs.all_changes_count || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/demo' || startsWith(github.ref, 'refs/heads/preview') || startsWith(github.ref, 'refs/heads/release') }}
+#    steps:
+#      - name: Cancel previous runs
+#        if: github.event_name != 'push'
+#        uses: styfle/cancel-workflow-action@0.11.0
+#        with:
+#          access_token: ${{ secrets.GITHUB_TOKEN }}
+#      - uses: actions/checkout@v3
+#      - uses: coursier/setup-action@v1
+#        with:
+#          jvm: temurin:1.11.0.17
+#      - name: Cache ivy packages
+#        uses: actions/cache@v3
+#        with:
+#          path: |
+#            ~/.ivy2/cache
+#            ~/.cache/coursier
+#            ~/.sbt
+#          key: sbt-cache-${{ hashFiles('**/*.sbt') }}
+#          restore-keys: sbt
+#      - uses: actions/download-artifact@v3
+#        with:
+#          name: build-target
+#      - name: Untar artifacts
+#        shell: bash
+#        run:  tar xfz target.tgz
+#      # We run k8s tests here instead of in integrationTests job because it causes RAM overhead and some other docker tests failing occasionally
+#      - uses: AbsaOSS/k3d-action@v2.4.0
+#        env:
+#          PROJECT_ROOT: ${{ github.workspace }}
+#        with:
+#          cluster-name: "k3s-default"
+#          k3d-version: "v5.4.9" # default version - change with caution, there was some problem with 500 exit codes for after upgrade
+#          args: >-
+#            --config=.k3d/single-cluster.yml
+#            --trace
+#      - name: Slow tests
+#        env:
+#          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+#          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+#          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+#        shell: bash
+#        run: ./ciRunSbt.sh designer/Slow/test liteK8sDeploymentManager/ExternalDepsTests/test schemedKafkaComponentsUtils/ExternalDepsTests/test liteKafkaComponentsTests/ExternalDepsTests/test
+#      - name: docker logs
+#        if: success() || failure()
+#        run: |
+#          docker logs k3d-k3s-default-server-0
+#          docker logs k3d-k3s-default-agent-0
+#          docker logs k3d-k3s-default-serverlb
+#      - name: Test Report
+#        if: success() || failure()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: SlowTests-results-${{ matrix.scalaVersion }}
+#          path: '**/test-reports/*.xml'
 
   frontendTests:
     name: FrontendTests
@@ -561,7 +561,7 @@ jobs:
   #TODO: extract to different workflow?
   publish:
     runs-on: ubuntu-latest
-    needs: [build, build-fe, setup, tests, crossCompile, integrationTests, slowTests, frontendTests, cypressTests]
+    needs: [build, build-fe, setup, tests, crossCompile, integrationTests, frontendTests, cypressTests]
     #TODO: should we publish everything on all those branches?
     if: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/demo' || startsWith(github.ref, 'refs/heads/preview') || startsWith(github.ref, 'refs/heads/release') }}
     env:
