skip cypress

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -373,7 +373,6 @@ jobs:
           path: designer/client/junit.xml
 
   cypressTests:
-    if: false
     name: CypressTests
     runs-on: self-hosted
     needs: [ build, build-fe, setup ]
@@ -391,131 +390,131 @@ jobs:
         uses: styfle/cancel-workflow-action@0.11.0
         with:
           access_token: ${{ secrets.GITHUB_TOKEN }}
-      # On self-hosted runners, docker can have some obsolete containers. Because of that, we clean them all
-      - name: Clean all docker containers
-        shell: bash
-        run: |
-          c=$(docker ps -q)
-          [[ $c ]] && docker kill $c || echo "No container run"
-      - uses: actions/checkout@v3
-      - name: Get Node.js version
-        id: nvm
-        run: echo "NODE_VERSION=$(cat designer/client/.nvmrc)" >> $GITHUB_OUTPUT
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
-      - uses: coursier/setup-action@v1
-        if: ${{ env.shouldBuildImage == 'true' }}
-        with:
-          jvm: temurin:1.11.0.17
-      - name: Download node modules
-        run: |
-          export npm_config_cache=$(mktemp -d)
-          npm config ls -l | grep cache
-          npm ci --no-audit --prefix designer/client
-          npm ci --no-audit --prefix designer/submodules
-          rm -rf $npm_config_cache
-      - uses: actions/download-artifact@v3
-        if: ${{ env.shouldBuildImage == 'true' }}
-        with:
-          name: build-target
-      - name: Untar artifacts
-        if: ${{ env.shouldBuildImage == 'true' }}
-        shell: bash
-        run:  tar xfz target.tgz
-      - uses: actions/download-artifact@v3
-        with:
-          name: build-fe-dist
-      - name: Untar fe artifacts
-        shell: bash
-        run:  tar xfz fe-dist.tgz
-      - name: set version
-        if: ${{ env.shouldBuildImage == 'true' }}
-        shell: bash
-        run: echo "NUSSKNACKER_VERSION=${{ needs.setup.outputs.nk_snapshot_version }}" >> $GITHUB_ENV
-      - name: Prepare docker
-        if: ${{ env.shouldBuildImage == 'true' }}
-        env:
-          addDevArtifacts: true
-        shell: bash
-        #Doc generation is rather costly, we don't want it in test image creation
-        run: sbt "set ThisBuild / version := \"$NUSSKNACKER_VERSION\"; set ThisBuild / packageDoc / publishArtifact := false; set Compile / doc / sources := Seq.empty" dist/Docker/publishLocal
-      - name: FE tests e2e on build docker image
-        if: ${{ env.shouldBuildImage == 'true' }}
-        env:
-          CYPRESS_SNAPSHOT_UPDATE: "true"
-          CYPRESS_BASE_URL: http://localhost:${{ env.BE_PORT }}
-          DOCKER_PULL_OPTION: never
-        shell: bash
-        run: |
-          cd designer/client
-          ! npx wait-on -t 250 tcp:localhost:${{ env.BE_PORT }} 2> /dev/null || (echo "Port: ${BE_PORT} already in use!" && exit 1)
-          npx start-server-and-test backend:docker ${{ env.BE_PORT }} test:e2e
-      - name: Determine docker tag version to use
-        if: ${{ env.shouldBuildImage == 'false' }}
-        shell: bash
-        run: |
-          # Take a look at build.sbt commonDockerSettings to see how this tag is determined. Thanks to fact that we publish all changes pushed to our "special" branches it should work quite correctly.
-          NK_REF_VERSION=`[ "${GITHUB_REF}" != "" ] && echo "${GITHUB_REF}" | sed -e 's/refs\/heads\///g' -e 's/[^a-zA-Z0-9._-]/\_/g' -e 's/$/-latest/' | xargs -I VER sh -c 'docker pull touk/nussknacker:VER > /dev/null && echo VER || echo ""'`
-          NK_BASE_REF_VERSION=`[ "${NK_REF_VERSION}" != "" ] && echo "${NK_REF_VERSION}" || [ "${GITHUB_BASE_REF}" != "" ] && echo "${GITHUB_BASE_REF}" | sed -e 's/refs\/heads\///g' -e 's/[^a-zA-Z0-9._-]/\_/g' -e 's/$/-latest/' | xargs -I VER sh -c 'docker pull touk/nussknacker:VER > /dev/null && echo VER || echo ""'`
-          echo "NUSSKNACKER_VERSION=`[ \"${NK_BASE_REF_VERSION}\" != \"\" ] && echo \"${NK_BASE_REF_VERSION}\" || echo staging-latest`" >> $GITHUB_ENV
-      - name: FE tests e2e on pulled image
-        if: ${{ env.shouldBuildImage == 'false' }}
-        env:
-          CYPRESS_SNAPSHOT_UPDATE: "true"
-        shell: bash
-        run: |
-          cd designer/client
-          ! npx wait-on -t 250 tcp:localhost:${{ env.BE_PORT }} 2> /dev/null || (echo "Port: ${BE_PORT} already in use!" && exit 1)
-          npx start-server-and-test backend:docker ${{ env.BE_PORT }} start-prod 3000 test:e2e
-      - name: Test Report
-        if: success() || failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: CypressTests-results
-          path: designer/client/cypress-test-results/*.xml
-      - name: Store test results
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: e2e-test-results
-          path: |
-            docs/autoScreenshotChangeDocs/
-            designer/client/cypress/**/__image_snapshots__/
-            designer/client/cypress/screenshots/
-            designer/client/cypress/videos/
-          if-no-files-found: ignore
-      - name: Create Pull Request
-        id: update_snapshots
-        uses: peter-evans/create-pull-request@v7
-        if: always() && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
-        env:
-          HASH: ${{ format('#{0}', github.event.number) }}
-          BRANCH: ${{ needs.setup.outputs.git_source_branch }}
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          base: ${{ env.BRANCH }}
-          branch: snapshots-patch/${{ env.BRANCH }}
-          title: Update Cypress snapshots in ${{ env.BRANCH }}
-          commit-message: Updated snapshots
-          body: Updated snapshots in ${{ github.event_name == 'pull_request' && env.HASH || env.BRANCH}}
-          labels: cypress
-      - name: Comment PR
-        if: ${{ always() && github.event_name == 'pull_request' && steps.update_snapshots.outputs.pull-request-number }}
-        uses: thollander/actions-comment-pull-request@v2
-        with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          message: |
-            ${{ steps.update_snapshots.outputs.pull-request-operation }}: #${{ steps.update_snapshots.outputs.pull-request-number }}
-            :warning: Be careful! Snapshot changes are not necessarily the cause of the error. Check the logs.
-          comment_tag: snapshots_pr
-      - name: Force fail if update PR created
-        if: ${{ always() && github.event_name == 'pull_request' && steps.update_snapshots.outputs.pull-request-number }}
-        uses: actions/github-script@v6.3.3
-        with:
-          script: |
-            core.setFailed('Snapshots updated, chceck comments!')
+#      # On self-hosted runners, docker can have some obsolete containers. Because of that, we clean them all
+#      - name: Clean all docker containers
+#        shell: bash
+#        run: |
+#          c=$(docker ps -q)
+#          [[ $c ]] && docker kill $c || echo "No container run"
+#      - uses: actions/checkout@v3
+#      - name: Get Node.js version
+#        id: nvm
+#        run: echo "NODE_VERSION=$(cat designer/client/.nvmrc)" >> $GITHUB_OUTPUT
+#      - name: Use Node.js ${{ matrix.node-version }}
+#        uses: actions/setup-node@v3
+#        with:
+#          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
+#      - uses: coursier/setup-action@v1
+#        if: ${{ env.shouldBuildImage == 'true' }}
+#        with:
+#          jvm: temurin:1.11.0.17
+#      - name: Download node modules
+#        run: |
+#          export npm_config_cache=$(mktemp -d)
+#          npm config ls -l | grep cache
+#          npm ci --no-audit --prefix designer/client
+#          npm ci --no-audit --prefix designer/submodules
+#          rm -rf $npm_config_cache
+#      - uses: actions/download-artifact@v3
+#        if: ${{ env.shouldBuildImage == 'true' }}
+#        with:
+#          name: build-target
+#      - name: Untar artifacts
+#        if: ${{ env.shouldBuildImage == 'true' }}
+#        shell: bash
+#        run:  tar xfz target.tgz
+#      - uses: actions/download-artifact@v3
+#        with:
+#          name: build-fe-dist
+#      - name: Untar fe artifacts
+#        shell: bash
+#        run:  tar xfz fe-dist.tgz
+#      - name: set version
+#        if: ${{ env.shouldBuildImage == 'true' }}
+#        shell: bash
+#        run: echo "NUSSKNACKER_VERSION=${{ needs.setup.outputs.nk_snapshot_version }}" >> $GITHUB_ENV
+#      - name: Prepare docker
+#        if: ${{ env.shouldBuildImage == 'true' }}
+#        env:
+#          addDevArtifacts: true
+#        shell: bash
+#        #Doc generation is rather costly, we don't want it in test image creation
+#        run: sbt "set ThisBuild / version := \"$NUSSKNACKER_VERSION\"; set ThisBuild / packageDoc / publishArtifact := false; set Compile / doc / sources := Seq.empty" dist/Docker/publishLocal
+#      - name: FE tests e2e on build docker image
+#        if: ${{ env.shouldBuildImage == 'true' }}
+#        env:
+#          CYPRESS_SNAPSHOT_UPDATE: "true"
+#          CYPRESS_BASE_URL: http://localhost:${{ env.BE_PORT }}
+#          DOCKER_PULL_OPTION: never
+#        shell: bash
+#        run: |
+#          cd designer/client
+#          ! npx wait-on -t 250 tcp:localhost:${{ env.BE_PORT }} 2> /dev/null || (echo "Port: ${BE_PORT} already in use!" && exit 1)
+#          npx start-server-and-test backend:docker ${{ env.BE_PORT }} test:e2e
+#      - name: Determine docker tag version to use
+#        if: ${{ env.shouldBuildImage == 'false' }}
+#        shell: bash
+#        run: |
+#          # Take a look at build.sbt commonDockerSettings to see how this tag is determined. Thanks to fact that we publish all changes pushed to our "special" branches it should work quite correctly.
+#          NK_REF_VERSION=`[ "${GITHUB_REF}" != "" ] && echo "${GITHUB_REF}" | sed -e 's/refs\/heads\///g' -e 's/[^a-zA-Z0-9._-]/\_/g' -e 's/$/-latest/' | xargs -I VER sh -c 'docker pull touk/nussknacker:VER > /dev/null && echo VER || echo ""'`
+#          NK_BASE_REF_VERSION=`[ "${NK_REF_VERSION}" != "" ] && echo "${NK_REF_VERSION}" || [ "${GITHUB_BASE_REF}" != "" ] && echo "${GITHUB_BASE_REF}" | sed -e 's/refs\/heads\///g' -e 's/[^a-zA-Z0-9._-]/\_/g' -e 's/$/-latest/' | xargs -I VER sh -c 'docker pull touk/nussknacker:VER > /dev/null && echo VER || echo ""'`
+#          echo "NUSSKNACKER_VERSION=`[ \"${NK_BASE_REF_VERSION}\" != \"\" ] && echo \"${NK_BASE_REF_VERSION}\" || echo staging-latest`" >> $GITHUB_ENV
+#      - name: FE tests e2e on pulled image
+#        if: ${{ env.shouldBuildImage == 'false' }}
+#        env:
+#          CYPRESS_SNAPSHOT_UPDATE: "true"
+#        shell: bash
+#        run: |
+#          cd designer/client
+#          ! npx wait-on -t 250 tcp:localhost:${{ env.BE_PORT }} 2> /dev/null || (echo "Port: ${BE_PORT} already in use!" && exit 1)
+#          npx start-server-and-test backend:docker ${{ env.BE_PORT }} start-prod 3000 test:e2e
+#      - name: Test Report
+#        if: success() || failure()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: CypressTests-results
+#          path: designer/client/cypress-test-results/*.xml
+#      - name: Store test results
+#        if: failure()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: e2e-test-results
+#          path: |
+#            docs/autoScreenshotChangeDocs/
+#            designer/client/cypress/**/__image_snapshots__/
+#            designer/client/cypress/screenshots/
+#            designer/client/cypress/videos/
+#          if-no-files-found: ignore
+#      - name: Create Pull Request
+#        id: update_snapshots
+#        uses: peter-evans/create-pull-request@v7
+#        if: always() && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
+#        env:
+#          HASH: ${{ format('#{0}', github.event.number) }}
+#          BRANCH: ${{ needs.setup.outputs.git_source_branch }}
+#        with:
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          base: ${{ env.BRANCH }}
+#          branch: snapshots-patch/${{ env.BRANCH }}
+#          title: Update Cypress snapshots in ${{ env.BRANCH }}
+#          commit-message: Updated snapshots
+#          body: Updated snapshots in ${{ github.event_name == 'pull_request' && env.HASH || env.BRANCH}}
+#          labels: cypress
+#      - name: Comment PR
+#        if: ${{ always() && github.event_name == 'pull_request' && steps.update_snapshots.outputs.pull-request-number }}
+#        uses: thollander/actions-comment-pull-request@v2
+#        with:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          message: |
+#            ${{ steps.update_snapshots.outputs.pull-request-operation }}: #${{ steps.update_snapshots.outputs.pull-request-number }}
+#            :warning: Be careful! Snapshot changes are not necessarily the cause of the error. Check the logs.
+#          comment_tag: snapshots_pr
+#      - name: Force fail if update PR created
+#        if: ${{ always() && github.event_name == 'pull_request' && steps.update_snapshots.outputs.pull-request-number }}
+#        uses: actions/github-script@v6.3.3
+#        with:
+#          script: |
+#            core.setFailed('Snapshots updated, chceck comments!')
 
   #TODO: extract to different workflow?
   publish:
